export type ShortDramaDraftVersion = 2

export type ShortDramaStudioMode = 'auto' | 'manual'

export type ShortDramaAutoStrategy = 'fill_only' | 'full_auto'

export type ShortDramaMediaKind = 'image' | 'video'

export type ShortDramaMediaStatus = 'running' | 'success' | 'error'

export type ShortDramaCreatedBy = 'auto' | 'manual'

export type ShortDramaFrameRole = 'start' | 'end'

export interface ShortDramaStyleSnapshot {
  presetId: string
  customText: string
  negativeText: string
  locked: boolean
}

export interface ShortDramaMediaVariant {
  id: string
  kind: ShortDramaMediaKind
  status: ShortDramaMediaStatus
  createdAt: number
  createdBy: ShortDramaCreatedBy

  // Model + prompt snapshot (for reproducibility)
  modelKey?: string
  promptSnapshot?: string
  styleSnapshot?: ShortDramaStyleSnapshot

  // Media payload
  sourceUrl?: string
  displayUrl?: string
  localPath?: string
  mediaId?: string

  // Video task id (if any)
  taskId?: string

  error?: string
}

export interface ShortDramaMediaSlot {
  id: string
  kind: ShortDramaMediaKind
  label?: string
  variants: ShortDramaMediaVariant[]
  selectedVariantId?: string
  /**
   * If true, auto mode must not change selectedVariantId implicitly.
   */
  selectionLockedByUser?: boolean
}

export interface ShortDramaStyle {
  presetId: string
  customText: string
  negativeText: string
  locked: boolean
}

export interface ShortDramaModels {
  analysisModelKey: string
  imageModelKey: string
  imageSize?: string
  imageQuality?: string
  videoModelKey: string
  videoRatio?: string
  videoDuration?: number
  videoSize?: string
}

export interface ShortDramaScriptSource {
  type: 'paste' | 'file' | 'canvas_text_node'
  fileName?: string
  nodeId?: string
}

export interface ShortDramaScript {
  text: string
  importedAt?: number
  source?: ShortDramaScriptSource
}

export interface ShortDramaCharacter {
  id: string
  name: string
  description: string

  /**
   * Character sheet: front/side/back + expressions (single composite image)
   */
  sheet: ShortDramaMediaSlot

  /**
   * Additional reference images
   */
  refs: ShortDramaMediaSlot[]

  /**
   * Preferred reference slot id (optional).
   */
  primaryRefSlotId?: string
}

export interface ShortDramaScene {
  id: string
  name: string
  description: string

  /**
   * Primary scene reference slot.
   */
  ref: ShortDramaMediaSlot

  /**
   * Additional reference images (optional).
   */
  refs?: ShortDramaMediaSlot[]
}

export interface ShortDramaShotFrame {
  role: ShortDramaFrameRole
  prompt: string
  slot: ShortDramaMediaSlot
}

export interface ShortDramaShot {
  id: string
  title: string

  sceneId?: string
  characterIds: string[]

  /**
   * Optional beat/intent summary (emotion/action/dialogue)
   */
  beat?: string

  /**
   * Optional video prompt (camera/motion). If empty, auto or manual may derive it.
   */
  videoPrompt: string

  frames: {
    start: ShortDramaShotFrame
    end: ShortDramaShotFrame
  }

  /**
   * Video versions slot. selectedVariantId is the "adopted" video.
   */
  video: ShortDramaMediaSlot
}

export interface ShortDramaGenerationPlan {
  /**
   * A free-form JSON payload generated by AI (optional).
   * Keep it as unknown to avoid breaking changes when iterating prompt schema.
   */
  raw?: unknown
}

export interface ShortDramaDraftV2 {
  version: ShortDramaDraftVersion
  projectId: string
  createdAt: number
  updatedAt: number

  title: string
  logline: string

  script: ShortDramaScript
  style: ShortDramaStyle
  models: ShortDramaModels

  characters: ShortDramaCharacter[]
  scenes: ShortDramaScene[]
  shots: ShortDramaShot[]

  plan?: ShortDramaGenerationPlan
}

